### ISSUE TITLE
请问想要实现循环的话，该如何实现呢

### ISSUE THREAD

**Issue by sulovely** [MrR0990/CalibrationView#1]
![image](https://user-images.githubusercontent.com/46919682/147734546-acda8242-5945-4ccf-89be-616729e05f8c.png)
这个实现的很好，如果有这种样式的，可以一直左右滑动没有边界的，大佬有什么好的思路提供么~

**Comment by MrR0990** [comment]
这个需求感觉挺好的,目前只有一个大概的思路,需要具体需要实现才能知道遇到什么问题,思路是否可行.
思路如下:
1: 获取组件所占区域的宽度,
2:计算每一格+线条所需要的宽度
3: 左右边际处理,也就是渐变以及超出部分如何计算以及处理
4:手势惯性处理
5:其他的参照组件本身的逻辑来处理

**Comment by MrR0990** [comment]
过段时间,我让这个组件也支持你这个需求,也一起验证下上面的那个思路.

**Comment by sulovely** [comment]
感谢~ 这边看网上一些实现方案，就是初始化时先根据初始坐标从中间开始画，左右各画一遍，然后在滑动的时候，不停的改变初始坐标，刷新绘制，但是分发事件的方式通过GestureDetector，快速滑动时有些问题，具体代码地址https://github.com/PandaQAQ/LoopScale，也可以借鉴一下

**Comment by MrR0990** [comment]
这个思路非常不错

**Comment by sulovely** [comment]
你这个组件到时候会支持这个需求么~

**Comment by MrR0990** [comment]
我可以试试

**Comment by sulovely** [comment]
感谢~如果没有循环，我这边还是挺好实现的，主要就是循环，然后脑袋就晕了...
